# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - crgarcia-budgetapp-app

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: dotnetsrc/budgetapp/BudgetApp/

    steps:
    - uses: actions/checkout@v2

    - name: Pwd
      run: pwd
    - name: LS
      run: ls
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crgarciabudgetappacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aee0e68d58654ff78aada149d852a36f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d4ea64c638804b19b193be9ac55f23dd }}
    
    - name: manual build
      run: 
        docker build -f Dockerfile -t crgarciabudgetappacr.azurecr.io/budgetapp:${{ github.sha }} ..
        docker push crgarciabudgetappacr.azurecr.io/budgetapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crgarcia-budgetapp-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e4c9512e909c4d6ebe30febaf5eb4de4 }}
        images: 'crgarciabudgetappacr.azurecr.io/budgetapp:${{ github.sha }}'
